stages:
  - build


variables:
  PROJECT_NAME: '${CI_PROJECT_NAME}'
  IMAGE_NAME: '${CI_REGISTRY}/${CI_PROJECT_NAME}'

build:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t  ${IMAGE_NAME} -f foreverloop/Dockerfile .  
    - docker push ${IMAGE_NAME}